name: Build and Publish SearchBharat

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to manually trigger a build from the GitHub UI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # We build on Mac, Linux, and Windows to generate .dmg, .AppImage, and .exe respectively
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish with Electron Builder
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist -- -p always
